openapi: 3.0.3
info:
  title: PERN To-Do API
  description: A project to practise PostgreSQL, Express, React, and Node
  version: 1.0.0
servers:
  - url: http://localhost:5000
tags:
  - name: todos
    description: Todo related routes
paths:
  /todos/:
    post:
      tags:
        - todos
      summary: Post a new todo
      description: Post a new todo
      operationId: Post
      requestBody:
        description: Post a new todo
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      responses:
        '201':
          description: New todo added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'       
    get:
      tags:
        - todos
      summary: Get all todos
      description: Get all todos
      operationId: Get all
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  /todos/{todo_id}:
    put:
      tags:
        - todos
      summary: Update todo by ID
      description: Update todo by ID
      operationId: Put
      parameters:
        - name: todo_id
          in: path
          description: ID of product to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Update todo by ID
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        required: true
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    delete:
      tags:
        - todos
      summary: Delete todo by ID
      description: Delete todo by ID
      operationId: delete
      parameters:
        - name: todo_id
          in: path
          description: ID of product to update
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: No Content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'  
components:
  schemas:
    Todo:
      type: object
      properties:
        description:
          type: string
          example: "Example: Configure Swagger"